name: Build, Upload and Commit Release

on:
  workflow_dispatch:  # This enables manual trigger from GitHub UI or API

jobs:
  build-upload-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetches all history for .Git commands
        token: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in GITHUB_TOKEN for operations

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Build wheels and source distribution
      run: |
        python -m pip install --upgrade build twine
        python setup.py bdist_wheel
        python setup.py sdist
        twine check dist/*

    - name: Upload to PyPI
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        echo "API tokens can be created at https://pypi.org/manage/account/token/"
        python -m twine upload -u __token__ -p $PYPI_API_TOKEN dist/*

    - name: Commit Release
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -u
        VERSION=$(python setup.py --version)
        git commit -m "Release v${VERSION}. [skip ci]"
        git tag v${VERSION}
        echo "A commit and tag for this release has been made. When you're ready run:"
        echo "    git push; sleep 60; git push --tags"
        shell: bash

    - name: Push changes
      run: |
        git push
        sleep 60
        git push --tags

